title: "Mi Digital Garden"
description: "Notes on my studies and experiences in the engineering and technology field"
baseurl: "/digital-garden"

source: .
destination: _site
collections:
  go:
    output: true
    permalink: /go/:name/
  good-practices:
    output: true
    permalink: /good-practices/:name/
  jekyll:
    output: true
    permalink: /jekyll/:name/
  networking:
    output: true
    permalink: /networking/:name/
  hardware:
    output: true
    permalink: /hardware/:name/


markdown: kramdown
highlighter: rouge