name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main
    paths:
      - 'jekyll-site/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'   # o la que prefieras
          bundler-cache: true

      - name: Install dependencies
        run: |
          cd jekyll-site
          bundle install

      - name: Build site
        run: |
          cd jekyll-site
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jekyll-site/_site
