name: Build and Deploy Jekyll

on:
  push:
    branches: [ main ]
    paths:
      - 'jekyll-site/**'
  workflow_dispatch:

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false        # no usamos Bundler

      - name: Install Jekyll (no Gemfile)
        run: |
          gem install jekyll -v 3.9.3
          gem install jekyll-feed jekyll-seo-tag
          gem install kramdown-parser-gfm     

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: |
          jekyll build -s jekyll-site -d jekyll-site/_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jekyll-site/_site